### ISSUE TITLE
Version info is wrong in 1.0.4 package

### ISSUE THREAD

**Issue by Chris-wa-He** [aws-samples/amazon-bedrock-client-for-mac#10]
<img width="320" alt="image" src="https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/52903590/a25f95bc-5ebf-447b-bb43-6b0cb7f8252d">

The about info for v1.0.4 is wrong. It still showing 1.0.2

**Comment by didhd** [comment]
Fixed in 1.0.5
