### ISSUE TITLE
Bedrock runtime update?

### ISSUE THREAD

**Issue by pklecha** [aws-samples/amazon-bedrock-client-for-mac#11]
Was this updated for Bedrock runtime update? I get the following error on all models (I do have access):

Error invoking the model: ValidationException(properties: AWSBedrockRuntime.ValidationException.Properties(message: Optional("1 validation error detected: Value 'anthropic.claude-v2:0:100k' at 'modelId' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}/[a-z0-9]{12})|(:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|([0-9]{12}:provisioned-model/[a-z0-9]{12})))|([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|(([0-9a-zA-Z][-]?)+)")), httpResponse: Status Code: http_status_400 x-amzn-RequestId: a1d2c37b-e82f-438e-b0bd-06c4815cbb58, x-amzn-ErrorType: ValidationException:http://internal.amazon.com/coral/com.amazon.bedrock/, Content-Type: application/json, Date: Thu, 07 Dec 2023 10:44:00 GMT, Connection: keep-alive, Content-Length: 493, message: Optional("1 validation error detected: Value 'anthropic.claude-v2:0:100k' at 'modelId' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}/[a-z0-9]{12})|(:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|([0-9]{12}:provisioned-model/[a-z0-9]{12})))|([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|(([0-9a-zA-Z][-]?)+)"), requestID: nil)

**Comment by didhd** [comment]
Fixed in 1.0.5

**Comment by pklecha** [comment]
The error is slightly different now but I still think it's related to Bedrock runtime change. Here's what I got now after attempting to use the latest version of the app (from Dec 10th, 2023):

Error invoking the model: ResourceNotFoundException(properties: AWSBedrockRuntime.ResourceNotFoundException.Properties(message: Optional("Could not resolve the foundation model from the provided model identifier.")), httpResponse: Status Code: http_status_404 Date: Tue, 12 Dec 2023 12:37:22 GMT, Connection: keep-alive, x-amzn-RequestId: 5437b2b4-dd1e-42a5-8eca-cda3e21c2d94, Content-Length: 88, Content-Type: application/json, x-amzn-ErrorType: ResourceNotFoundException:http://internal.amazon.com/coral/com.amazon.bedrock/, message: Optional("Could not resolve the foundation model from the provided model identifier."), requestID: nil)
