### ISSUE TITLE
400 error when calling titan-image-generator-v1

### ISSUE THREAD

**Issue by JasonWeill** [aws-samples/amazon-bedrock-client-for-mac#12]
When I'm authenticated to an account with access to all Bedrock models, when I send a text prompt to titan-image-generator-v1, I get an error:

> Error invoking the model: ValidationException(properties: AWSBedrockRuntime.ValidationException.Properties(message: Optional("Malformed input request, please reformat your input and try again.")), httpResponse: Status Code: http_status_400 x-amzn-RequestId: de13b7f8-67fb-4ada-a3cf-9bd40805d05b, Content-Type: application/json, x-amzn-ErrorType: ValidationException:http://internal.amazon.com/coral/com.amazon.bedrock/, Content-Length: 80, Connection: keep-alive, Date: Thu, 07 Dec 2023 22:04:37 GMT, message: Optional("Malformed input request, please reformat your input and try again."), requestID: nil)

Making the same request using the Bedrock image playground works as expected.

**Comment by didhd** [comment]
Fixed in 1.0.5
