### ISSUE TITLE
error 2 when launching the app

### ISSUE THREAD

**Issue by dianjunren** [aws-samples/amazon-bedrock-client-for-mac#13]
Hello I got the error below when I launch the application. Can you advise how to fix the error? Thanks

<img width="262" alt="image" src="https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/17145797/65023791-5e30-483d-a851-1eb8b4921f46">

**Comment by didhd** [comment]
Did you check this? https://github.com/aws-samples/amazon-bedrock-client-for-mac?tab=readme-ov-file#troubleshooting

**Comment by dianjunren** [comment]
I checked but no troubleshooting talks about the error 2. I do see #2 on the troubleshooting is for error 1, not error 2.

**Comment by didhd** [comment]
Fixed application to give user more detailed error string:
<img width="260" alt="image" src="https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/17061938/e14ca618-e82c-4941-bfa4-923b0bdb9dea">
