### ISSUE TITLE
truncated responses

### ISSUE THREAD

**Issue by odilon-goulart** [aws-samples/amazon-bedrock-client-for-mac#17]
truncated responses, only partial responses, sometimes half of the sentence.
Also, when asking for code examples, it just print the first sentence and the code is missing

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Sonoma
 - Version [e.g. 22] 14.3.1
 - Browser [e.g. chrome, safari] Bedrock for Mac

**Comment by odilon-goulart** [comment]
<img width="1503" alt="Screenshot 2024-02-20 at 15 40 25" src="https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/42016104/43e3ab54-fcb7-4b77-bfb0-11f0b1b131fd">

**Comment by odilon-goulart** [comment]
what harry potter school magic is doing on the left?

**Comment by odilon-goulart** [comment]
as you can see, no responses at all. Also it's look like the previous question is not being taken in consideration.

**Comment by didhd** [comment]
Thank you for informing me about the issue! Only Llama and Titan models are aware of the previous conversation history, and it seems that the command model can also be easily modified to support this.

**Comment by didhd** [comment]
This is referring to the sidebar displaying the last message content, and now that we're using claude haiku instead of claude instant, I've updated the prompts so it should summarize better. Since this doesn't seem to be an actual issue, I'll go ahead and close it out.
