### ISSUE TITLE
Should not be allowed to change model mid-conversation

### ISSUE THREAD

**Issue by NathanHazout** [aws-samples/amazon-bedrock-client-for-mac#18]
I started a conversation with Claude, then at the top dropdown changed it to Titan Image Generator.  
I didn't actually change the endpoint, but it changed it in the top bar.

I think that to avoid confusion, once a session is started the top bar should become read-only.

<img width="1347" alt="Screenshot 2024-02-26 at 15 56 46" src="https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/329834/f0ffbb7c-fa3f-4074-84af-4423a059cf59">

Also, it seems that toggling between conversations does not update the top bar, the model name does not reflect the actual model selected for this conversation.

**Comment by didhd** [comment]
@NathanHazout Thank you for your feedback. The reason the dropdown remains enabled is solely to allow users to start a new conversation with a different model if desired. We acknowledge that the current UI implementation may cause confusion regarding model selection, and we will consider alternative approaches to make this process more intuitive in future updates.
