### ISSUE TITLE
any plan to support non default profile

### ISSUE THREAD

**Issue by qiufengliu** [aws-samples/amazon-bedrock-client-for-mac#20]
Is there any plan to support non default profile, It should give user an option to select other profile, Thanks

**Comment by didhd** [comment]
@qiufengliu Thank you for your suggestion regarding support for non-default profiles.

Fortunately, this feature has been added in v1.2.0. The Amazon Bedrock Client for Mac now allows you to use multiple AWS profiles.

We will continue to incorporate user feedback to drive further improvements to the product. Please feel free to share any other suggestions you may have. Your insights help shape the roadmap.

**Comment by hrzbrg** [comment]
@didhd I just comment here before I create a new case. I saw you added profile support by reading `/.aws/credentials`. It would be great if the App would support SSO profiles stored in `/.aws/config` similar to how the AWS CLI uses it.

**Comment by didhd** [comment]
@hrzbrg I'm working on developing that now.

**Comment by didhd** [comment]
@hrzbrg Fixed in v1.2.1
