### ISSUE TITLE
Significant frontend app lag

### ISSUE THREAD

**Issue by aaron-gray** [aws-samples/amazon-bedrock-client-for-mac#22]
**Describe the bug**
After a long conversation, the UI is extremely laggy, even for non-Bedrock activities. Just resizing the window or trying to enter text in the input field is very slow and delayed.

**To Reproduce**
Engage in a long conversation with a LLM in Bedrock, and observe as basic UI slows to a crawl.

**Expected behavior**
The length of a chat should not impact the responsiveness of the local client app.

**Desktop (please complete the following information):**
 - OS: Sonoma 14.4

**Comment by ArlindNocaj** [comment]
The UI is lagging a lot and is not really usable.

**Comment by didhd** [comment]
@ArlindNocaj Thank you for bringing this to our attention. I apologize for the inconvenience caused by the UI lag. Providing a smooth user experience is a top priority for me, and I am actively working to improve the performance.

**Comment by loneizhao** [comment]
Same for me . especially when uploading a 2.9M pic and ask questions. Notice also that bedrock client process is occupying a lot of system resource and could be the reason of lag

**Comment by aaron-gray** [comment]
Hi--any update on this bug? This does make it very difficult to use for anything other than the simplest task. Any fix would be greatly appreciated 🙏

**Comment by didhd** [comment]
Performance has been improved in https://github.com/aws-samples/amazon-bedrock-client-for-mac/releases/tag/v1.1.10. We are continuing to work on improving performance.

**Comment by didhd** [comment]
@aaron-gray @ArlindNocaj @loneizhao

Performance has been significantly improved in v1.2.0 of the Amazon Bedrock Client for Mac, released after substantial code work. I apologize for the delay, but we have been actively working to enhance the performance. The new version should provide a much smoother user experience, even during extended conversations. Please let me know if you continue to experience any lag or performance issues after updating to v1.2.0.
