### ISSUE TITLE
Copy pasting of output not possible

### ISSUE THREAD

**Issue by ArlindNocaj** [aws-samples/amazon-bedrock-client-for-mac#23]
**Describe the bug**
Generate some long text e.g. with multiple xml tags.
Copy paste of complete output not possible.

<img width="1071" alt="Screenshot 2024-03-26 at 13 11 54" src="https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/2978097/06b47087-c6d3-44ad-9900-ae715e07a0ed">

Try to copy paste the full generated output. Only single paragraphs can be selected.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by didhd** [comment]
You could use copy button under the text.
