### ISSUE TITLE
Chat gets stuck due to system errors

### ISSUE THREAD

**Issue by michaellatman** [aws-samples/amazon-bedrock-client-for-mac#24]
**Describe the bug**
When the system encounters errors such as ThrottlingException or ValidationException, the chat can get stuck indefinitely, preventing the user from continuing the conversation. This occurs because the system does not handle these errors gracefully and does not provide a way for the user to resume the chat once the underlying issue is resolved.

**To Reproduce**
1. Send multiple requests to the system, triggering a ThrottlingException. Alternatively expire your default profile to cause an auth error.
2. Attempt to send a request with multiple "user" roles in a single row, triggering a ValidationException.
3. Observe that the chat becomes stuck and the user is unable to continue the conversation.

**Expected behavior**
When the system encounters errors, it should handle them gracefully and provide a way for the user to resume the chat once the underlying issue is resolved. This could involve concatenating the user's previous messages that resulted in errors and allowing the user to continue the conversation.

**Additional context**
Providing a way for the user to continue the chat after system errors would improve the user experience and prevent frustration when the chat gets stuck. Concatenating the previous messages that resulted in errors could help the user understand the context and pick up where they left off.

![image](https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/236019/4ba93862-9828-4d4b-8208-d4ec8d56b127)

**Comment by didhd** [comment]
@michaellatman I acknowledge this bug, and we will address it soon. To improve the user experience, we plan to implement proper handling so that conversations do not get interrupted when errors like ThrottlingException or ValidationException occur. We are currently reviewing specific solutions to resolve this issue. Thank you for bringing this to our attention.

**Comment by didhd** [comment]
Fixed in v1.2.1
