### ISSUE TITLE
Detected as Malware

### ISSUE THREAD

**Issue by crnc3vic** [aws-samples/amazon-bedrock-client-for-mac#28]
Hi there,

Following the recent update, this app has been identified as malware and cannot be run unless you choose "Bypass malware protection." However, this creates a significant security hazard that I think few people will accept.

I have Sonoma 14.4.1 (23E224)

Do you have any intentions to fix this issue?

**Comment by didhd** [comment]
@crnc3vic I think it is duplicate of #26, looking into it. Sorry for the inconvenience.

**Comment by didhd** [comment]
@crnc3vic I'm not sure of the exact cause of the issue, but occasionally, after some time passes, the package seems to be recognized as malware for no known reason. It's actually not malware, so you can be reassured. Also, the error shouldn't appear anymore as I've repackaged it with the same version 1.1.8. Can you check it?

**Comment by crnc3vic** [comment]
It appears to be solved for the time being. Thanks for checking into this so promptly.
