### ISSUE TITLE
Allow multiple conversation threads per model

### ISSUE THREAD

**Issue by KoStard** [aws-samples/amazon-bedrock-client-for-mac#3]
## Description 

The Bedrock Mac client currently maintains the conversation history within a session when switching between models. However, there is only one linear conversation thread per model.

It would be very useful to have the ability to maintain multiple simultaneous conversation threads for each model. This way, users could switch between different topic threads without losing context.

For example, I may want to discuss topic A with model X, then switch to discuss topic B, and then go back to pick up where I left off in topic A. Currently this is not easily possible.

## Proposed Solution

- Allow users to create separate conversation threads with bookmarks/titles
- Persist threads for each model, even across app reloads
- Enable quick switching between active threads for a model

This would enable much more flexibility in conversations and reduce context switching costs.

## Additional Details

The immediate conversation history within a session is currently preserved nicely. The limitations are around:

- Losing history on app restart 
- No support for multiple threaded discussions per model

Please let me know if any other details would help! I'm happy to collaborate on designing and implementing this feature.

**Comment by didhd** [comment]
Fixed in v1.1.0
