### ISSUE TITLE
Paste image to the chat from the buffer

### ISSUE THREAD

**Issue by yeralin** [aws-samples/amazon-bedrock-client-for-mac#30]
**Is your feature request related to a problem? Please describe.**
Allow pasting images from the buffer to the chat.

**Describe the solution you'd like**
When you have an image payload in your buffer, you can paste the image directly in the chat of the AWS Bedrock client.

**Describe alternatives you've considered**
Currently, you can do it manually by pressing the image icon on the chat text box:
<img width="38" alt="image" src="https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/8620461/c16d91ac-1a5a-4861-ad2a-a1e4a411f0db">

**Comment by dgallitelli** [comment]
+1 to this request - would be incredibly useful!

**Comment by didhd** [comment]
Fixed in https://github.com/aws-samples/amazon-bedrock-client-for-mac/releases/tag/v1.1.10
