### ISSUE TITLE
Latest release is not installable or compatible with Mac 13.6.6 (Ventura).

### ISSUE THREAD

**Issue by orsenthil** [aws-samples/amazon-bedrock-client-for-mac#35]
I tried to latest release  https://github.com/aws-samples/amazon-bedrock-client-for-mac/releases/tag/v1.1.10 on Mac 13.6.6 (Ventura).

The artifact wasn't compatible.

**Comment by didhd** [comment]
Could you check if this version is installable? 
https://github.com/aws-samples/amazon-bedrock-client-for-mac/actions/runs/9721836783/artifacts/1650868656

**Comment by didhd** [comment]
@orsenthil I released a new 1.1.10 package. This should probably solve the issue.
