### ISSUE TITLE
[BUG] Missing Chat History when upgrading Client Application to v1.2.0

### ISSUE THREAD

**Issue by taylanu** [aws-samples/amazon-bedrock-client-for-mac#37]
**Describe the bug**
There is a bug in the latest version of Bedrock for Mac Client. Customers upgrading from V1.1x.x to v1.2 will be unable to view their previous chat messages that were handled by previous clients.

**To Reproduce**
Install Bedrock for Mac [v1.1.10](https://github.com/aws-samples/amazon-bedrock-client-for-mac/releases/tag/v1.1.10) or earlier. 
2. Start a chat message and close the application
3. Install Bedrock Client for Mac [v1.2.0](https://github.com/aws-samples/amazon-bedrock-client-for-mac/releases/tag/v1.2.0)

**Expected behavior**
Customers would expect their previous chat messages on previous versions of the Application to be present on this latest version of the Client Application

**Environment (required):**
 - macOS version: Sonoma 14.5
 - Amazon Bedrock Client for Mac version: 1.11.1
 - Target Client Version: 1.2.0

**Log Files (optional)**
Please attach the log files located in `~/Amazon Bedrock Client/logs/`. These logs are crucial for diagnosing the issue.
^ Logs unavailable for this issue.

**Screenshots (optional)**
<img width="3008" alt="Bedrock Client v1 2 Missing Chat History" src="https://github.com/aws-samples/amazon-bedrock-client-for-mac/assets/9167137/cfd4f672-833e-4b27-bea7-4d0d4efa924d">

**Additional context (optional)**

**Comment by didhd** [comment]
@taylanu  Unfortunately, we had to discard the previous logic for handling chat history during the optimization process for the new version 1.2.0 of the Amazon Bedrock Client for Mac. This resulted in the unintended consequence of customers being unable to view their previous chat messages when upgrading from earlier versions like v1.1.10.

While we understand the frustration this causes by losing access to prior chat history, the decision was made to prioritize performance and stability improvements in the latest release. Maintaining backwards compatibility for chat history would have significantly complicated the development effort and delayed the rollout of other critical enhancements.

We sincerely apologize for this inconvenience and the lack of a workaround currently. Preserving chat history across major version upgrades is certainly valuable for our customers, and we will strongly consider reintroducing this functionality in a future update once we have the appropriate engineering resources available. Thank you for your understanding as we continue to iterate and improve the Amazon Bedrock experience.

**Comment by taylauna** [comment]
Hi @didhd,
Thank you so much for your thoughtful and considerate response. 
I'm in the process of migrating/deleting old chat logs from my v1.1.10 to v1.2.0, running both applications side by side.
The Conversation history and logic in v1.2.0 has been incredibly smooth, using it daily as a part of my workflow. 

Amazing work,
Taylan Unal

**Comment by taylanu** [comment]
Hi @didhd,
Thank you so much for your thoughtful and considerate response.
I'm in the process of migrating/deleting old chat logs from my v1.1.10 to v1.2.0, running both applications side by side.
The Conversation history and logic in v1.2.0 has been incredibly smooth, using it daily as a part of my workflow.

Amazing work,
Taylan Unal

**Comment by taylanu** [comment]
Hi @didhd,
Thank you so much for your thoughtful and considerate response.
I'm in the process of migrating/deleting old chat logs from my v1.1.10 to v1.2.0, running both applications side by side.
The Conversation history and logic in v1.2.0 has been incredibly smooth, using it daily as a part of my workflow.

Amazing work,
Taylan Unal
