### ISSUE TITLE
App crashes when closing settings popup

### ISSUE THREAD

**Issue by KoStard** [aws-samples/amazon-bedrock-client-for-mac#4]
## Description

When opening the settings popup in the Amazon Bedrock Mac Client app and clicking the close button, the entire app crashes. 

### Steps to reproduce

1. Open the Amazon Bedrock Mac Client app
2. Open the settings popup with command + `,`
3. Click the close button on the settings popup
4. The entire app crashes

### Expected behavior

Closing the settings popup should close the popup without crashing the app.

### Actual behavior

Clicking the close button on the settings popup crashes the entire app.

### Environment

  - Mac OS version: 13.5.2

**Comment by didhd** [comment]
fixed in v1.0.4
