### ISSUE TITLE
[FEATURE]  Hide the dropdown selector for the model 

### ISSUE THREAD

**Issue by sbhal** [aws-samples/amazon-bedrock-client-for-mac#43]
**Feature description**
I want the ability to hide the dropdown selector for the model selection in the user interface.

**Problem it solves (optional)**
I am aiming for minimal look of UI.

**Proposed solution**
Model select can be part of settings dialog.

**Alternatives considered (optional)**
Alternatively ability to hide menubar similar to how one can hide tab-bar.

**Comment by ronchengang** [comment]
+1
My administrator didn't give me bedrock:ListFoundationModels permission, but this client has to select a model before it can be used. I think adding a default model name to the settings window will solve this problem.

**Comment by didhd** [comment]
Commit 1274170
Preview
[Give feedback](https://gh.io/new-commit-details-feedback)
[didhd](https://github.com/aws-samples/amazon-bedrock-client-for-mac/commits?author=didhd)
didhd
committed
4 days ago
·
refactor: improve code readability, logging, and default model selection logic

**Comment by didhd** [comment]
@ronchengang You can choose the model from the dropdown list.
