### ISSUE TITLE
[FEATURE] Ability to add a system prompt

### ISSUE THREAD

**Issue by niyazpk** [aws-samples/amazon-bedrock-client-for-mac#45]
**Feature description**
I want the ability to add a system prompt (or something similar) where I can give a bunch of default instructions the model should adhere to. Right now I have to provide my default instructions for some tasks in every thread, which becomes tedious.

**Comment by didhd** [comment]
Fixed in 1.2.3

**Comment by didhd** [comment]
<img width="500" alt="image" src="https://github.com/user-attachments/assets/6e0e372e-4634-40b9-b147-5075cad6477a">
