### ISSUE TITLE
[FEATURE] User persona profiles

### ISSUE THREAD

**Issue by Flolight** [aws-samples/amazon-bedrock-client-for-mac#47]
**Feature description**
Allow the user to select a user profile. This can be a system prompt or concatenated prompt so that I can Have a specific profile when I want the assistance to behave as a persona (like a writer or coding expert...)

**Problem it solves (optional)**
I'm always frustrated when I need to use persona inside my conversation. I need to re-write it and this makes me store this somewhere outside the tool, not practical.

**Proposed solution**
We can have a menu some where to create or select a persona for the current chat 

**Alternatives considered (optional)**

**Additional context (optional)**

**Environment (optional)**
 - macOS version: [e.g. 13.0]
 - Amazon Bedrock Client for Mac version: [e.g. 1.0.0]

**Comment by niyazpk** [comment]
Similar ticket: https://github.com/aws-samples/amazon-bedrock-client-for-mac/issues/45

**Comment by didhd** [comment]
Fixed in v1.2.3

**Comment by didhd** [comment]
<img width="500" alt="image" src="https://github.com/user-attachments/assets/390ff6cd-7968-44a3-aa68-7ef333e657ba">
