### ISSUE TITLE
[FEATURE] Add support for Sonnet 3.5 v2

### ISSUE THREAD

**Issue by sbhal** [aws-samples/amazon-bedrock-client-for-mac#49]
**Feature description**
Using `Version 1.2.2 (1.2.2)` and don't see model `anthropic.claude-3-5-sonnet-20241022-v2:0`.

**Comment by niyazpk** [comment]
Also, please add support for `anthropic.claude-3-5-haiku-20241022-v1:0`

**Comment by didhd** [comment]
It already supports sonnet v2 on us-west-2

**Comment by hyperlink** [comment]
Hello @didhd,

Our account currently has the model enabled only in us-east-1, and accessing it requires an inference profile. Could the client be updated to support this method?

**Comment by didhd** [comment]
Hi @hyperlink, I will try to update this in next version.

**Comment by didhd** [comment]
Apologies for the delay in addressing this feature request. I'm happy to announce that this has been implemented in v1.2.6 (12f6194).

The latest version includes:
- Support for Claude 3.5 Sonnet v2 model
- Cross-region inference profile support (commit 69abe0a)
- Integration with inference profiles for all regions including us-east-1

This should now work regardless of which region your Sonnet v2 model is enabled in, thanks to the new inference profile integration.

Please update to v1.2.6 and let us know if you experience any issues.

/cc @sbhal @hyperlink @niyazpk
