### ISSUE TITLE
[BUG] AWS Credential refresh not getting picked up

### ISSUE THREAD

**Issue by niyazpk** [aws-samples/amazon-bedrock-client-for-mac#53]
**Describe the bug**
I have a CLI that refreshes the AWS credentials continuously on my machine. For the last many months, the app has been able to pick up the refreshed credentials without any issues.

Now in `1.2.3`, I have to restart the app for it to pick up the credentials once they expire.

**Environment (required):**
 - macOS version: 15.1
 - Amazon Bedrock Client for Mac version: 1.2.3

**Comment by didhd** [comment]
Sorry, will be fixing right now.
