### ISSUE TITLE
[FEATURE] Cross Region Inference

### ISSUE THREAD

**Issue by Flolight** [aws-samples/amazon-bedrock-client-for-mac#56]
**Feature description**
Add support for Cross Region Inference.

**Comment by didhd** [comment]
This feature request has been implemented in commit 69abe0a and released in v1.2.6 (12f6194).

You can now use inference profiles across regions. The implementation includes:
- Integration with AWS SDK v1.0.62
- Merged inference profiles with foundation models
- Added listInferenceProfiles method

Closing this as the requested feature is now available. Please update to the latest version to use cross-region inference.

/cc @Flolight
