### ISSUE TITLE
[FEATURE] Inference profile support for latest Nova and Llama 3.2 model

### ISSUE THREAD

**Issue by XenMe** [aws-samples/amazon-bedrock-client-for-mac#60]
**Feature description**
Inference profile support for latest Nova and Llama 3.2 model

**Problem it solves (optional)**
The latest model such as Nova and Llama 3.2 only support invoke via Inference profile.

**Comment by taylanu** [comment]
Hi XenMe, 
I have made updates and tested support for Amazon Nova Models (Streaming/Non-Streaming) locally, I am working towards a pull request on that front.
I'll look into adding Llama 3.2 Models to that update as well, depending on level of effort.

Thanks,
taylanu@

**Comment by didhd** [comment]
This issue has been resolved in v1.2.6 which includes support for Nova models. The implementation was merged in PR #61.

Closing this as the feature request has been completed.

For users experiencing issues with Nova models, please ensure you're running v1.2.6 or later of the Amazon Bedrock Client for Mac.
