### ISSUE TITLE
Amazon_Bedrock.BedrockError error 1.

### ISSUE THREAD

**Issue by peterdotcode** [aws-samples/amazon-bedrock-client-for-mac#8]
After launching the app or changing region I get the error prompt;

`
ERROR
The operation couldn’t be completed. (Amazon_Bedrock.BedrockError error 1.)
`

**Comment by didhd** [comment]
Can you check this? 
https://github.com/aws-samples/amazon-bedrock-client-for-mac#2-issues-with-aws-tokens-or-amazon_bedrockbedrockerror-error-1
